// NYC Neighborhood data and adjacency mapping
// Used for finding comparable sales in same or adjacent neighborhoods

// Neighborhood adjacency map - neighborhoods that border each other
// This is a simplified version focused on major investment neighborhoods
export const NEIGHBORHOOD_ADJACENCIES: Record<string, string[]> = {
  // Manhattan - Downtown
  "ALPHABET CITY": ["EAST VILLAGE", "LOWER EAST SIDE"],
  "EAST VILLAGE": ["ALPHABET CITY", "LOWER EAST SIDE", "GRAMERCY", "NOHO", "GREENWICH VILLAGE-CENTRAL"],
  "LOWER EAST SIDE": ["EAST VILLAGE", "ALPHABET CITY", "CHINATOWN", "LITTLE ITALY", "TWO BRIDGES"],
  "GREENWICH VILLAGE-CENTRAL": ["EAST VILLAGE", "NOHO", "SOHO", "WEST VILLAGE", "GRAMERCY"],
  "GREENWICH VILLAGE-WEST": ["WEST VILLAGE", "SOHO", "GREENWICH VILLAGE-CENTRAL"],
  "WEST VILLAGE": ["GREENWICH VILLAGE-CENTRAL", "GREENWICH VILLAGE-WEST", "SOHO", "TRIBECA", "CHELSEA"],
  "SOHO": ["GREENWICH VILLAGE-CENTRAL", "WEST VILLAGE", "NOHO", "LITTLE ITALY", "TRIBECA", "CHINATOWN"],
  "NOHO": ["EAST VILLAGE", "SOHO", "GREENWICH VILLAGE-CENTRAL", "LITTLE ITALY"],
  "TRIBECA": ["SOHO", "WEST VILLAGE", "CHINATOWN", "FINANCIAL", "CIVIC CENTER"],
  "CHINATOWN": ["LOWER EAST SIDE", "LITTLE ITALY", "SOHO", "TRIBECA", "CIVIC CENTER", "TWO BRIDGES"],
  "LITTLE ITALY": ["LOWER EAST SIDE", "SOHO", "NOHO", "CHINATOWN"],
  "FINANCIAL": ["TRIBECA", "CIVIC CENTER"],
  "CIVIC CENTER": ["TRIBECA", "CHINATOWN", "FINANCIAL", "TWO BRIDGES"],
  "TWO BRIDGES": ["LOWER EAST SIDE", "CHINATOWN", "CIVIC CENTER"],
  
  // Manhattan - Midtown
  "CHELSEA": ["WEST VILLAGE", "FLATIRON", "CLINTON", "MIDTOWN WEST", "GRAMERCY"],
  "FLATIRON": ["CHELSEA", "GRAMERCY", "MIDTOWN EAST", "MIDTOWN WEST", "KIPS BAY"],
  "GRAMERCY": ["EAST VILLAGE", "FLATIRON", "KIPS BAY", "MURRAY HILL", "CHELSEA"],
  "KIPS BAY": ["GRAMERCY", "MURRAY HILL", "FLATIRON", "MIDTOWN EAST"],
  "MURRAY HILL": ["GRAMERCY", "KIPS BAY", "MIDTOWN EAST", "TURTLE BAY"],
  "MIDTOWN EAST": ["FLATIRON", "MURRAY HILL", "TURTLE BAY", "MIDTOWN WEST", "MIDTOWN CBD"],
  "MIDTOWN WEST": ["CHELSEA", "FLATIRON", "MIDTOWN EAST", "CLINTON", "MIDTOWN CBD"],
  "MIDTOWN CBD": ["MIDTOWN EAST", "MIDTOWN WEST", "TURTLE BAY"],
  "CLINTON": ["CHELSEA", "MIDTOWN WEST", "UPPER WEST SIDE (59-79)", "MANHATTANVILLE"],
  "TURTLE BAY": ["MURRAY HILL", "MIDTOWN EAST", "UPPER EAST SIDE (59-79)"],
  
  // Manhattan - Uptown
  "UPPER EAST SIDE (59-79)": ["TURTLE BAY", "UPPER EAST SIDE (79-96)", "UPPER WEST SIDE (59-79)", "YORKVILLE"],
  "UPPER EAST SIDE (79-96)": ["UPPER EAST SIDE (59-79)", "YORKVILLE", "CARNEGIE HILL"],
  "YORKVILLE": ["UPPER EAST SIDE (59-79)", "UPPER EAST SIDE (79-96)", "CARNEGIE HILL", "EAST HARLEM"],
  "CARNEGIE HILL": ["UPPER EAST SIDE (79-96)", "YORKVILLE", "EAST HARLEM"],
  "UPPER WEST SIDE (59-79)": ["CLINTON", "UPPER EAST SIDE (59-79)", "UPPER WEST SIDE (79-96)", "LINCOLN SQUARE"],
  "UPPER WEST SIDE (79-96)": ["UPPER WEST SIDE (59-79)", "LINCOLN SQUARE", "MANHATTAN VALLEY", "MORNINGSIDE HEIGHTS"],
  "LINCOLN SQUARE": ["UPPER WEST SIDE (59-79)", "UPPER WEST SIDE (79-96)", "CLINTON"],
  "MANHATTAN VALLEY": ["UPPER WEST SIDE (79-96)", "MORNINGSIDE HEIGHTS", "HARLEM-CENTRAL"],
  "MORNINGSIDE HEIGHTS": ["UPPER WEST SIDE (79-96)", "MANHATTAN VALLEY", "HARLEM-CENTRAL", "MANHATTANVILLE"],
  
  // Manhattan - Harlem
  "HARLEM-CENTRAL": ["MORNINGSIDE HEIGHTS", "MANHATTAN VALLEY", "HARLEM-UPPER", "EAST HARLEM", "HARLEM-EAST"],
  "HARLEM-UPPER": ["HARLEM-CENTRAL", "HARLEM-EAST", "WASHINGTON HEIGHTS LOWER", "INWOOD"],
  "HARLEM-EAST": ["HARLEM-CENTRAL", "HARLEM-UPPER", "EAST HARLEM"],
  "EAST HARLEM": ["YORKVILLE", "CARNEGIE HILL", "HARLEM-CENTRAL", "HARLEM-EAST"],
  "MANHATTANVILLE": ["MORNINGSIDE HEIGHTS", "HARLEM-CENTRAL", "CLINTON"],
  "WASHINGTON HEIGHTS LOWER": ["HARLEM-UPPER", "WASHINGTON HEIGHTS UPPER"],
  "WASHINGTON HEIGHTS UPPER": ["WASHINGTON HEIGHTS LOWER", "INWOOD"],
  "INWOOD": ["WASHINGTON HEIGHTS UPPER", "HARLEM-UPPER"],
  
  // Brooklyn - North
  "WILLIAMSBURG-NORTH": ["WILLIAMSBURG-CENTRAL", "GREENPOINT", "WILLIAMSBURG-EAST"],
  "WILLIAMSBURG-CENTRAL": ["WILLIAMSBURG-NORTH", "WILLIAMSBURG-SOUTH", "WILLIAMSBURG-EAST", "GREENPOINT"],
  "WILLIAMSBURG-SOUTH": ["WILLIAMSBURG-CENTRAL", "WILLIAMSBURG-EAST", "BEDFORD STUYVESANT", "CLINTON HILL"],
  "WILLIAMSBURG-EAST": ["WILLIAMSBURG-NORTH", "WILLIAMSBURG-CENTRAL", "WILLIAMSBURG-SOUTH", "BUSHWICK"],
  "GREENPOINT": ["WILLIAMSBURG-NORTH", "WILLIAMSBURG-CENTRAL"],
  
  // Brooklyn - Central/West
  "DOWNTOWN-FULTON FERRY": ["BROOKLYN HEIGHTS", "DOWNTOWN-FULTON MALL", "DUMBO"],
  "BROOKLYN HEIGHTS": ["DOWNTOWN-FULTON FERRY", "COBBLE HILL", "DOWNTOWN-FULTON MALL", "DOWNTOWN-METROTECH"],
  "COBBLE HILL": ["BROOKLYN HEIGHTS", "CARROLL GARDENS", "BOERUM HILL", "GOWANUS"],
  "CARROLL GARDENS": ["COBBLE HILL", "RED HOOK", "GOWANUS", "PARK SLOPE"],
  "BOERUM HILL": ["COBBLE HILL", "FORT GREENE", "GOWANUS", "PARK SLOPE"],
  "FORT GREENE": ["BOERUM HILL", "CLINTON HILL", "DOWNTOWN-METROTECH", "PROSPECT HEIGHTS"],
  "CLINTON HILL": ["FORT GREENE", "WILLIAMSBURG-SOUTH", "BEDFORD STUYVESANT", "PROSPECT HEIGHTS"],
  "GOWANUS": ["COBBLE HILL", "CARROLL GARDENS", "BOERUM HILL", "PARK SLOPE", "RED HOOK"],
  "PARK SLOPE": ["CARROLL GARDENS", "GOWANUS", "BOERUM HILL", "PROSPECT HEIGHTS", "WINDSOR TERRACE", "PROSPECT PARK SOUTH"],
  "PROSPECT HEIGHTS": ["FORT GREENE", "CLINTON HILL", "PARK SLOPE", "CROWN HEIGHTS"],
  "RED HOOK": ["CARROLL GARDENS", "GOWANUS"],
  
  // Brooklyn - Central/East
  "BEDFORD STUYVESANT": ["WILLIAMSBURG-SOUTH", "CLINTON HILL", "CROWN HEIGHTS", "BUSHWICK", "OCEAN HILL"],
  "CROWN HEIGHTS": ["PROSPECT HEIGHTS", "BEDFORD STUYVESANT", "PROSPECT LEFFERTS GARDENS", "EAST FLATBUSH"],
  "BUSHWICK": ["WILLIAMSBURG-EAST", "BEDFORD STUYVESANT", "OCEAN HILL", "EAST NEW YORK"],
  "OCEAN HILL": ["BEDFORD STUYVESANT", "BUSHWICK", "BROWNSVILLE"],
  "BROWNSVILLE": ["OCEAN HILL", "EAST NEW YORK", "EAST FLATBUSH"],
  "EAST NEW YORK": ["BUSHWICK", "BROWNSVILLE", "CYPRESS HILLS"],
  
  // Brooklyn - South
  "PROSPECT LEFFERTS GARDENS": ["CROWN HEIGHTS", "FLATBUSH-EAST", "EAST FLATBUSH"],
  "FLATBUSH-EAST": ["PROSPECT LEFFERTS GARDENS", "FLATBUSH-CENTRAL", "EAST FLATBUSH"],
  "FLATBUSH-CENTRAL": ["FLATBUSH-EAST", "FLATBUSH-NORTH", "FLATBUSH-LEFFERTS GARDEN"],
  "EAST FLATBUSH": ["CROWN HEIGHTS", "PROSPECT LEFFERTS GARDENS", "FLATBUSH-EAST", "BROWNSVILLE", "CANARSIE"],
  "WINDSOR TERRACE": ["PARK SLOPE", "KENSINGTON", "PROSPECT PARK SOUTH"],
  "KENSINGTON": ["WINDSOR TERRACE", "BOROUGH PARK", "FLATBUSH-CENTRAL"],
  
  // Bronx - South
  "MOTT HAVEN/PORT MORRIS": ["MELROSE/CONCOURSE", "HUNTS POINT", "LONGWOOD"],
  "MELROSE/CONCOURSE": ["MOTT HAVEN/PORT MORRIS", "HIGHBRIDGE/MORRIS HEIGHTS", "MORRISANIA/LONGWOOD"],
  "HUNTS POINT": ["MOTT HAVEN/PORT MORRIS", "LONGWOOD", "SOUNDVIEW"],
  "LONGWOOD": ["MOTT HAVEN/PORT MORRIS", "HUNTS POINT", "MORRISANIA/LONGWOOD"],
  "MORRISANIA/LONGWOOD": ["MELROSE/CONCOURSE", "LONGWOOD", "CROTONA PARK"],
  
  // Bronx - Central
  "HIGHBRIDGE/MORRIS HEIGHTS": ["MELROSE/CONCOURSE", "UNIVERSITY HEIGHTS/FORDHAM", "TREMONT"],
  "TREMONT": ["HIGHBRIDGE/MORRIS HEIGHTS", "BELMONT", "CROTONA PARK"],
  "BELMONT": ["TREMONT", "FORDHAM", "BRONX PARK"],
  "FORDHAM": ["BELMONT", "UNIVERSITY HEIGHTS/FORDHAM", "KINGSBRIDGE/JEROME PARK"],
  "UNIVERSITY HEIGHTS/FORDHAM": ["HIGHBRIDGE/MORRIS HEIGHTS", "FORDHAM", "KINGSBRIDGE/JEROME PARK"],
  
  // Bronx - East
  "SOUNDVIEW": ["HUNTS POINT", "PARKCHESTER", "CASTLE HILL/UNIONPORT"],
  "PARKCHESTER": ["SOUNDVIEW", "CASTLE HILL/UNIONPORT", "WESTCHESTER"],
  "CASTLE HILL/UNIONPORT": ["SOUNDVIEW", "PARKCHESTER", "THROGS NECK"],
  
  // Queens - West
  "ASTORIA": ["LONG ISLAND CITY", "SUNNYSIDE/WOODSIDE", "JACKSON HEIGHTS", "STEINWAY"],
  "LONG ISLAND CITY": ["ASTORIA", "SUNNYSIDE/WOODSIDE", "HUNTERS POINT"],
  "HUNTERS POINT": ["LONG ISLAND CITY", "SUNNYSIDE/WOODSIDE"],
  "SUNNYSIDE/WOODSIDE": ["ASTORIA", "LONG ISLAND CITY", "HUNTERS POINT", "JACKSON HEIGHTS", "MASPETH", "ELMHURST"],
  "JACKSON HEIGHTS": ["ASTORIA", "SUNNYSIDE/WOODSIDE", "ELMHURST", "CORONA", "EAST ELMHURST"],
  "ELMHURST": ["SUNNYSIDE/WOODSIDE", "JACKSON HEIGHTS", "CORONA", "REGO PARK", "MASPETH"],
  "CORONA": ["JACKSON HEIGHTS", "ELMHURST", "FLUSHING-NORTH", "FOREST HILLS"],
  
  // Queens - Central
  "REGO PARK": ["ELMHURST", "FOREST HILLS", "MIDDLE VILLAGE"],
  "FOREST HILLS": ["REGO PARK", "CORONA", "KEW GARDENS", "RICHMOND HILL"],
  "KEW GARDENS": ["FOREST HILLS", "RICHMOND HILL", "BRIARWOOD"],
  "FLUSHING-NORTH": ["CORONA", "FLUSHING-SOUTH", "WHITESTONE"],
  "FLUSHING-SOUTH": ["FLUSHING-NORTH", "FRESH MEADOWS", "BAYSIDE"],
  
  // Queens - South
  "RICHMOND HILL": ["FOREST HILLS", "KEW GARDENS", "OZONE PARK", "WOODHAVEN"],
  "WOODHAVEN": ["RICHMOND HILL", "OZONE PARK", "HOWARD BEACH"],
  "OZONE PARK": ["RICHMOND HILL", "WOODHAVEN", "HOWARD BEACH", "SOUTH OZONE PARK"],
  
  // Staten Island
  "ST. GEORGE": ["STAPLETON-CLIFTON", "NEW BRIGHTON"],
  "STAPLETON-CLIFTON": ["ST. GEORGE", "PARK HILL", "GRYMES HILL"],
  "NEW BRIGHTON": ["ST. GEORGE", "WEST NEW BRIGHTON"],
  "WEST NEW BRIGHTON": ["NEW BRIGHTON", "PORT RICHMOND"],
  "PORT RICHMOND": ["WEST NEW BRIGHTON", "MARINERS HARBOR"],
};

/**
 * Get adjacent neighborhoods for a given neighborhood
 */
export function getAdjacentNeighborhoods(neighborhood: string): string[] {
  const upper = neighborhood.toUpperCase();
  
  // Direct lookup
  if (NEIGHBORHOOD_ADJACENCIES[upper]) {
    return NEIGHBORHOOD_ADJACENCIES[upper];
  }
  
  // Try partial match (some neighborhoods have variations)
  for (const [key, adjacents] of Object.entries(NEIGHBORHOOD_ADJACENCIES)) {
    if (key.includes(upper) || upper.includes(key)) {
      return adjacents;
    }
  }
  
  return [];
}

/**
 * Check if two neighborhoods are the same or adjacent
 */
export function areNeighborhoodsCompatible(n1: string, n2: string): boolean {
  const upper1 = n1.toUpperCase();
  const upper2 = n2.toUpperCase();
  
  // Same neighborhood
  if (upper1 === upper2) return true;
  if (upper1.includes(upper2) || upper2.includes(upper1)) return true;
  
  // Check adjacency
  const adjacents = getAdjacentNeighborhoods(upper1);
  return adjacents.some(adj => 
    adj === upper2 || adj.includes(upper2) || upper2.includes(adj)
  );
}

/**
 * Get all compatible neighborhoods (self + adjacent)
 */
export function getCompatibleNeighborhoods(neighborhood: string): string[] {
  const upper = neighborhood.toUpperCase();
  const adjacents = getAdjacentNeighborhoods(upper);
  return [upper, ...adjacents];
}
